

\begin{table}[hb!]
\centering
  
\begin{tabular}{ p{\textwidth } }
  \hline
  
  \textbf{Sphere of Influence} \\
  \hline

 
  \begin{description}

    \item[\textbf{Input}]: Define the gene expression data and the network model

    \item[For] putative driver gene $i$ 

    \begin{enumerate}

        \item Calculate the Spearman rank correlation $\rho_k$ between the 
        	  expression of gene $k$ and gene $i$ across all the conditions
        	  in the expression matrix for every other gene $k$: 
            $\rho_1,\rho_2,\dots,\rho_{N-1}$
            (where $N$ is the number of genes both assayed and on the
            network)

       	\item Calculate the total observed correlation between gene $i$
       		  and its neighbors: $\sum_{k=1}^{M} |\rho_k|$ where the correlations
       		  $\rho_k$ are indexed so that the first $M$ genes are in the
       		  neighborhood of gene $i$

       	\item Compute the distribution of total correlation under the null by
       		    generating $N_{\text{Sphere}}$ null total correlations. To
              generate each null total correlation:

        \begin{enumerate}

            \item Bootstrap from the correlations calculated in Step (1)

            \item Preserve the gene indices's so that the first 
              re-sampled correlation is assigned to gene $k=1$, etc and
              recalculate the total correlation as in Step (2)

        \end{enumerate}


       	\item Compute $p^i_{\text{Sphere}}$ by counting the the proportion of 
       		  null sums greater than or equal to the observed sum. 
            If $p^i_{\text{Sphere}} = 0$, set 
       		  $p^i_{\text{Sphere}}=\frac{1}{N_\text{Sphere}+1}$


    \end{enumerate}


    \item[\textbf{Output}]: Return $p^i_{\text{Sphere}}$


  \end{description} \\
  
  \hline
\end{tabular}

\caption{The Sphere of Influence procedure tests if a putative driver gene
is more correlated with its network neighbors than with a random set of genes.}

\label{tab:procedure-sphere}
\end{table}


